version: "3.9"
services:
  jenkins:
    build:
      context: ""
    container_name: "jenkins"
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8080:8080"
    volumes:
      - "/opt/jenkins_home/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
